### ISSUE TITLE
Two instances of rvplayer folder is created, one is left after Uninstall

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#21]
**How to Duplicate**
Run new installer
Uninstall
Go to ./config there is an rvplayer folder there however other files are deleted

**Expected**
All artifacts of RV deleted

**Environment**
Ubuntu 14.04 64bit
Ubuntu 15.10 32bit

**Note**
Similar behavior seen in #26

**Comment by tejohnso** [comment]
See
https://github.com/Rise-Vision/rise-launcher-electron/pull/116

**Comment by lapinnoir** [comment]
@tejohnso thanks, closing issue
