### ISSUE TITLE
UI: Network checks don't reflect in the UI during install

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#22]
**How to duplicate**
You may need slightly 'off' connection but run the Installer, it will then state that there is no Internet connectivity even though there is.  In the logs below there is a network timeout for google.com.  This fails the connectivity check so the user is then taken to a message prompt stating that there is no Internet connectivity (there is - since it passed the other network checks) and to input proxy details.  

**Expected**
Maybe a better message would be to prompt user to go through installation again - there is no button to start again - only to Cancel (which closes the Installer) or to add proxy details and Continue.

Edit: I had the same message for Windows 7.  I pressed Continue and could try to go ahead with the rest of the installation process - but I think the initial messaging may require improvement.  However when I was able to continue for Win 7, I was unable to complete installation (whether or not this was due to the network check is unclear)

**In the logs:**

**installer-events.log**

2015/12/18 12:30:41 - Checking network requirements
2015/12/18 12:30:42 - Checking network connectivity - http://rvashow2.appspot.com
2015/12/18 12:30:42 - Checking network connectivity - http://rvashow.appspot.com
2015/12/18 12:30:42 - Checking network connectivity - http://storage-dot-rvaserver2.appspot.com
2015/12/18 12:30:42 - Checking network connectivity - http://p.jwpcdn.com/6/5/jwpsrv.js
2015/12/18 12:30:42 - Checking network connectivity - https://talkgadget.google.com
2015/12/18 12:30:42 - Checking network connectivity - https://store.risevision.com
2015/12/18 12:30:42 - Checking network connectivity - https://accounts.google.com/ManageAccount
2015/12/18 12:30:43 - Checking network connectivity - http://s3.amazonaws.com
**2015/12/18 12:30:51 - Error: network timeout at: http://www.google.com/**

**installer-detail.log**
2015/12/18 12:29:53
started
2015/12/18 12:30:51 - **Error: network timeout at: http://www.google.com/**
network prereq error
2015/12/18 12:33:28
all closed

**Environment**
Ubuntu 14.04 64bit

**Comment by tejohnso** [comment]
Can't really say why google timed out and the others didn't, but if they don't all pass it's not going to allow the process to continue.  Maybe it was something to do with the network being slightly off.  Can you try this again and see if it's a persistent problem?   And if so, can you explain how the network is slightly off?

**Comment by lapinnoir** [comment]
@tejohnso 

I think that for the user this is going to be an obstacle:
- In the logs the reason why the connectivity check was a network timeout for one of the checks.  The user normally does not go through logs to find out why
- From a CS troubleshooting perspective (if the user approaches CS about this) it's difficult to troubleshoot to the user (without asking for additional info) other than requesting to to try installing it again.  Even then they may get network timeout on another check (ie somewhat related, see #28 )
- From the user perspective they will find this message confusing - ie I had the connectivity fail message despite already having access Internet access.  They will wonder why they are seeing this message despite in "user land" (ie not looking at logs) their Internet is fine

With the network connectivity fails, not persistent.

**Comment by tejohnso** [comment]
We don't want the user to go through the logs.  We retry the connection several times and if it can't complete we send them to CS.  I'm not sure what we would tell the user on the UI.  Their internet seems fine, and for some reason some of the network checks aren't passing.  I don't see what we do there aside from getting CS involved.  Anything else leads the user down a debugging path which I think we want to  avoid.  Having them go to CS and then having CS ask for more information from them (or look at BQ) is what we actually want to have happen.   @ByronDarlison  comments?

**Comment by ByronDarlison** [comment]
@tejohnso @lapinnoir @robb-price couple of questions:

What is the error message that the User sees when this happens?

Should they have the ability to try again?

If X % fail, rather than everything, should we give them the option to continue but warn them that there might be a problem?

Thanks!

**Comment by lapinnoir** [comment]
@ByronDarlison @tejohnso 
On Win 7:  I can press Continue on that dialogue box and continue on with the network connectivity checks.  But if the checks are failing (either due to one or many fails) I won't be able to move past this box and finish the installation.

I've pressed Continue and can't move past.

After a few minutes I've exited (Cancel) then ran the installer again.  This time I was able to install.

In another test on Win 7 (#28 https://github.com/Rise-Vision/rise-launcher/issues/28) I failed the network connectivity test at first try but it ended with the prompt box that was due to another Request timeout error.

**Comment by ByronDarlison** [comment]
@lapinnoir okay. @tejohnso can you recap for me how you recommend we correct this situation? Thanks!

**Comment by tejohnso** [comment]
I think we should add more attempts to establish a connection and make sure there's a delay between each attempt.  I'm not sure if that's the case right now.  It might be firing off 10 attempts within one second or something.  

After that I think we leave it as is and see if it's a problem many users are encountering.  Then we should revisit before starting to upgrade existing users.

**Comment by ByronDarlison** [comment]
@tejohnso okay. @lapinnoir @robb-price do you agree with @tejohnso 's recommendation?

**Comment by lapinnoir** [comment]
@tejohnso @ByronDarlison  I agree with the two.  Does it need to be 100% pass, or what about 80% pass for all checks?

**Comment by ByronDarlison** [comment]
@lapinnoir @tejohnso I think something less than 100% would work. What do you guys think?

**Comment by tejohnso** [comment]
Addressed here
https://github.com/Rise-Vision/rise-launcher-electron/pull/120

I think we should see what happens with this fix and if we still get intermittent errors then start accepting less than 100%.  I don't think it's very useful to tell the user "you *may* have problems" though.  What are they supposed to do with that information?

**Comment by lapinnoir** [comment]
@tejohnso @ByronDarlison Ok.  If we get to the stage of acceptance for less than 100%, the next question is what % is enough to pass.  What about passing one network check being enough to confirm connectivity (not level/quality of connectivity) and finish the installer?

**Comment by tejohnso** [comment]
@lapinnoir Good question.  The point of doing this check is to make sure the user doesn't run into problems later on.  If we set it to only one check, then we're not really achieving the goal.  We might as well say the fact that they were able to download the installer from the internet is sufficient to prove their network works.  We have all these different sites being checked to try to make it fail *before* they accept that their player is going to work.   So I"m not a fan of the idea that we'd accept less than 100%.  I'm hoping the improvements to the retrying gets us what we need.

**Comment by ByronDarlison** [comment]
Good point @tejohnso. Let's see what happens. Thanks

**Comment by lapinnoir** [comment]
@tejohnso @ByronDarlison closing issue since fix for this deployed in 334
