### ISSUE TITLE
Two instances of Startup shortcut with different targets in properties after running new installation over old Installer

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#24]
**How to duplicate**
This occurs for the following tests:

Test 1:
1. Install existing Player using existing installer with autostart enabled.
2. Replace RiseVisionPlayer.exe with new Installer
3. Reboot machine and confirm the old installer successfully upgrades to the new installer

Test 2:
1. Install existing Player using existing installer with autostart enabled.
2. Download new installer and run it, confirming that it installs correctly over top of the old installer

After upgrading or installing over the top of the old installer, there are two instances of Startup shortcut with different targets in properties after running new installation over old Installer:

Shortcut with Electron icon (new Installer) "Rise Vision Player" targets: 
"C:\Users\Rise Win 10 Test\AppData\Local\RVPlayer\Installer\installer.exe" --unattended

Shortcut with the RV icon (current Installer) "Start Rise Vision Player" targets:
"C:\Users\Rise Win 10 Test\AppData\Local\RVPlayer\RiseVisionPlayer.exe" /S

**Expected result**
One shortcut targeting one property

Environment
Windows 10 32bit

**Comment by fjvallarino** [comment]
@lapinnoir @tejohnso See https://github.com/Rise-Vision/rise-launcher-electron/pull/119

**Comment by lapinnoir** [comment]
@fjvallarino @tejohnso thanks, closing issue
