### ISSUE TITLE
For more details visit [link] does not work in the Displays setup menu

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#25]
**How to Duplicate**
Install RV Player
Add invalid DisplayID

![linkdoesntwork](https://cloud.githubusercontent.com/assets/5868781/11915575/5d29bc28-a67a-11e5-98ab-113f4ca7f4e7.png)

**Expect outcome**
Link should go to the final Create A Display page

**Environment**
Found during Win 10 32bit testing but applicable with other OS

**Comment by fjvallarino** [comment]
@lapinnoir This is not related to the installer itself, but to https://github.com/Rise-Vision/viewer

**Comment by lapinnoir** [comment]
@fjvallarino thanks, issue submitted in https://github.com/Rise-Vision/viewer/issues/76 - closing this one.
