### ISSUE TITLE
 rvplayer folder remains in AppData/Local after Uninstall command

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#26]
**How to duplicate**
Install
Run the Uninstall Start menu option

The Rvplayer shortcut is not in startup folder, there are no Start/Edit/Uninstall options for RV in the Start menu option but the rvplayer folder remains in AppData/Local

See http://recordit.co/mpD1jxv1eG

**Expected outcome**
All RV artifacts deleted following Uninstall command either on the Startup or clicking on the Uninstall file in the folder

**Environment**
Win 10 32bit

**Note**
Similar behavior seen in https://github.com/Rise-Vision/rise-launcher/issues/44 for Linux

**Comment by tejohnso** [comment]
@fjvallarino can you reproduce this?

**Comment by fjvallarino** [comment]
@lapinnoir @tejohnso I'm not able to reproduce this issue. I guess it can happen if you call the "Uninstall" link while having the rvplayer folder open in Windows Explorer or similar; Windows is not really keen on deleting stuff currently in use.

**Comment by lapinnoir** [comment]
@fjvallarino I will revisit again

**Comment by lapinnoir** [comment]
closing to see if issue replicates 340#artifacts

**Comment by lapinnoir** [comment]
@fjvallarino @tejohnso Reopening this issue because I can confirm that Uninstall option on Startup doesn't work including rebooting and running uninstall option again.  See http://recordit.co/mpD1jxv1eG

I've edited the original issue with the link

**Comment by lapinnoir** [comment]
Also: the recording is from 340#artifacts version of Installer

**Comment by tejohnso** [comment]
@fjvallarino Can you check into this windows uninstall issue?

**Comment by fjvallarino** [comment]
@lapinnoir @tejohnso I think this is because the user name has white spaces. I'll add quotation marks to the batch file command.

**Comment by fjvallarino** [comment]
@lapinnoir @tejohnso This build should fix the issue: https://circleci.com/gh/Rise-Vision/rise-launcher-electron/360#artifacts

**Comment by lapinnoir** [comment]
@tejohnso @fjvallarino Ok - closing and using 360 to test
