### ISSUE TITLE
Message unclear following failed installation

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#28]
Related to #22 but this is on another OS (Win 7 32bit).

**How to duplicate**
1. New install
2. After lack of connectivity (prompt to input proxy details) message, press Continue and try to complete installation 
3. On failing the installation process you will see the prompt:
"An unknown error has occurred.  Please try again or post a question to http://community.risevision.com"

From a CS perspective it is difficult to troubleshoot what the error may be until additional details that the user can obtain with the installation fail.  It's difficult to then know what exactly the issue is, if it's because they failed the network connectivity requirements or due to another process.

On exiting seeing this message the user sees this prompt:

<img width="425" alt="screen shot 2015-12-18 at 4 32 48 pm" src="https://cloud.githubusercontent.com/assets/5868781/11915666/93ac9f40-a67f-11e5-965a-360ff7dc4ca3.png">
- On 'What settings are applied?' link the user is taken to the Program Compatibility Assistant
- It is unclear if the user should click on 'This program installed correctly' or 'Reinstall using Recommended Settings'

The timestamp of the above screenshot was taken at 4:32.28pm EST so looking at the **installer-detail.log** it states

```
2015/12/18 16:29:08 - An unknown error has occurred.  Please try again or post a question to http://community.risevision.com.
{ message: 'Error downloading http://install-versions.risevision.com/RisePlayer-2015-12-17-16-00.tar.gz',
  error: 
 { message: 'Request timed out',
     error: 'http://install-versions.risevision.com/RisePlayer-2015-12-17-16-00.tar.gz' } }
2015/12/18 16:32:21
all closed

```

**Environment**
Win 7 32bit

**Comment by tejohnso** [comment]
@fjvallarino Do we have some way of turning off that compatibility assistant prompt?

As for the error, @lapinnoir in that failure case the user is going to go to CS and at that point I think they'd be asked to supply their log file.   We don't want to ask the user to try to figure it out on their own at that point or complicate the error message any further.

@ByronDarlison I propose we close this unless @lapinnoir or @fjvallarino have any suggestions.

**Comment by ByronDarlison** [comment]
@tejohnso curious, why is this an unknown error in the error message? We know what the error is don't we? And if we do, why can't we state it and ask the User to post the error they are getting in the community and we will do our best to help the. Okay?

BTW @lapinnoir awesome job of finding these!!!

**Comment by tejohnso** [comment]
@fjvallarino I think something like this should work.  Then we could add more user friendly messages to other sub-processes as well.
https://github.com/Rise-Vision/rise-launcher-electron/compare/chore/fix-unknown-error-overuse

**Comment by fjvallarino** [comment]
@tejohnso Looks good

**Comment by fjvallarino** [comment]
@lapinnoir @tejohnso See https://github.com/Rise-Vision/rise-launcher-electron/pull/117

**Comment by lapinnoir** [comment]
@fjvallarino @tejohnso thanks, closing issue
