### ISSUE TITLE
Publisher unverified message

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#29]
**How to Duplicate**
Install

Prompt "The publisher could not be verified" and "This file does not have a valid digital signature that verifies its publisher." 

**Expected**
No prompt message

**Environment**
Win 7 32bit

**Comment by fjvallarino** [comment]
@lapinnoir @tejohnso This cannot be fixed until we have the certificate for signing the installer. I'd rather remove this issue to avoid confusion.

**Comment by tejohnso** [comment]
@ByronDarlison Any objections to closing this?

**Comment by ByronDarlison** [comment]
@lapinnoir @fjvallarino @tejohnso @robb-price I am okay with closing it. Can you include the link to the card that is tracking this future work in Trello here before closing though. Thanks

**Comment by tejohnso** [comment]
Trello card: https://trello.com/c/xtxy2M8e

**Comment by lapinnoir** [comment]
@tejohnso Also FYI for the Win 8 message appearing:
Windows Smartscreen prevented an unrecognised app from starting.  Running this app might put your PC at risk.
