### ISSUE TITLE
rvplayer ./config/autostart after unchecking Autostart 

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#32]
**How to Duplicate**
Clean install
Check Add to Startup
There is rvplayer in ./config/autostart
User changes mind, does not want Autostart
Run Installer
Unchecks Autostart
There is still rvplayer in ./config/autostart 

**Expected outcome**
No ./config/rvplayer in autostart when a user unchecks Autostart in Installer (after the first install where the user initially checks Autostart)

**Environment**
Linux Ubuntu 14.04

**Comment by tejohnso** [comment]
@lapinnoir The installer either adds or doesn't add autostart based on the checkbox. It doesn't remove autostart.  I think if the user wants to stop starting on bootup, they would do it from their OS startup menu.  
Maybe we could also add a "remove from startup" option on our Rise Player program group.

@ByronDarlison  I suggest we talk about this as a future enhancement.

**Comment by ByronDarlison** [comment]
@tejohnso good suggestion re. adding to Rise Player program group. @lapinnoir do you concur? @robb-price ?

And if all are in agreement @tejohnso @fjvallarino what would it take in terms of points to implement this? Thanks

**Comment by tejohnso** [comment]
@ByronDarlison It's very similar to the other program group icons we have so it should be a small change.  On the same order as the other fixes we've been making today.

**Comment by ByronDarlison** [comment]
@tejohnso okay. I think we should add this. @lapinnoir @robb-price you concur?

**Comment by lapinnoir** [comment]
@ByronDarlison @tejohnso sounds good

**Comment by tejohnso** [comment]
@lapinnoir I've implemented it through the installer.  It was easier than adding start menu options.  We can always add those options later, and they'll trigger the same code in the installer.    Doing some testing now.

**Comment by lapinnoir** [comment]
@tejohnso to confirm is this in 334#artifacts?

**Comment by tejohnso** [comment]
@lapinnoir yes, it is there.
