### ISSUE TITLE
Incorrect UI message following failed network check

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#33]
**How to duplicate**
Install

See UI prompt that the Install was a success however the Continue button is greyed and unable to Start Player following the install

![screen shot 2015-12-21 at 1 50 02 pm](https://cloud.githubusercontent.com/assets/5868781/11939461/50d30502-a7f0-11e5-813a-57c4763183c6.png)

When pressing Cancel taken to this prompt:

![screen shot 2015-12-21 at 2 07 24 pm](https://cloud.githubusercontent.com/assets/5868781/11939449/4570f566-a7f0-11e5-9fa8-36f07921c6e2.png)

**Expected**
1. If Install completes and user sees prompt to Start Player, the user should be able to press Continue rather than see the greyed out Continue button
2. If Install did not complete not installed correctly, user should not see the UI "Rise Player Installation" success message

**Environment**
Win 7 32bit

**Comment by fjvallarino** [comment]
@lapinnoir @tejohnso See https://github.com/Rise-Vision/rise-launcher-electron/pull/117

**Comment by lapinnoir** [comment]
@fjvallarino @tejohnso thanks, closing issue
