### ISSUE TITLE
Current Windows Installer is downloading Chrome 47 on second launch even after the upgrade to 47 is turned off

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-launcher#34]
<b>How it works now:</b>
1. Download the installer from help.risevision.com, and run it. Notice that it installs Chrome 46.
2. Kill Java instances and restart Player, or just reboot the machine. Notice upon Player starting again, to begins downloading Chrome 47.

For further clarification: https://goo.gl/LWdtgG

<b>How it should work:</b>
Since upgrades for the Windows player have been disabled, it should not upgrade to 47.

**Comment by robb-price** [comment]
@fjvallarino shared RisePlayer 2015.10.12.15.11, this one does not appear to upgrade to 47 after restarting Player.

@tejohnso @alanclayton This may be a moot point since there are so many Chrome 47's Windows machines out there. We can discuss tomorrow.

**Comment by tejohnso** [comment]
@robb-price in any case I think this is fixed now, correct?
@fjvallarino FYI

**Comment by robb-price** [comment]
@tejohnso That's correct, however we should ensure the new installer does not have the same problem, which I don't think it does. So we can close this.
