### ISSUE TITLE
Installer process runs again upon reboot 

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#36]
**How to Duplicate**
Two scenarios
1. Finish install -  select Autostart - Don't input Display ID, Quit - Reboot
2. Finish install -  select Autostart - Input Display ID - Reboot

Upon reboot for both I am taken to the Rise Player installation process (checking components, install complete) again.  This process does not involve user interaction (ie pressing Continue, etc).  After the installation process, the Display starts.

**Expected outcome**
After selecting Autostart and on reboot for both scenarios, I see the presentation itself (if I input the correct DisplayID) or I see the Display prompt to input DisplayID if I have not already added this in.  I don't see the UI for the Rise Player installation process.

I've made a note of this only because this is a difference with the current installer which starts to DisplayID without seeing anything in the UI in between.

**Environment**
Windows 8.1 64 bit
In the Startup Folder there is a shortcut for Rise Vision Player linking to installer.exe

Observed in Linux 15.10 32bit, Linux 14.04 64bit
In the .config/autostart folder the rvplayer shortcut leads to /rvplayer/Installer/installer/ -unattended

**Comment by tejohnso** [comment]
@lapinnoir This is working as expected.  In both new and old installer the "installer" runs again on bootup.  This is because the installer needs to check for any updates and install them as necessary.   In the old one there is no UI but this one has one so it's visible.  We've set it up so that it requires no user interaction from autostart.

**Comment by lapinnoir** [comment]
@tejohnso thanks - closing issue
