### ISSUE TITLE
Failed network check message text does not include prompt for user to press Continue

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#37]
See:
![ctacontinue](https://cloud.githubusercontent.com/assets/5868781/11961488/ee1aea44-a8a6-11e5-87e4-2c613786be92.png)

**Expected**
Adding call to action within the initial copy to prompt users that they can press Continue

**Environment**
Win 7 32bit

**Comment by tejohnso** [comment]
I think we can change **"Otherwise please contact support."** to **"Otherwise please contact support or click continue to try again."**
@ByronDarlison @lapinnoir Sound good?

**Comment by lapinnoir** [comment]
@tejohnso:
 "Otherwise please click Continue below or go to community.risevision.com for Support"

- the click Continue I think should be emphasized so that the user can try again 
- when contacting Support there should be an additional call to action so I've added the web link.

@robb-price @ByronDarlison

**Comment by robb-price** [comment]
@lapinnoir @ByronDarlison @tejohnso My vote would be to send them to the community.

I don't think the Continue button needs to be emphasized personally, and I agree with adding the community link, as if they are having trouble getting online past a proxy, it's likely they won't be able to click a link to go to the community.

**Comment by ByronDarlison** [comment]
Agreed. Thanks

**Comment by tejohnso** [comment]
@lapinnoir please recheck using 340

**Comment by lapinnoir** [comment]
@tejohnso :+1:
