### ISSUE TITLE
Unclear on progress message

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#38]
**How to Duplicate**
Run 2 x Win 7 VM on two different networks.

**Notes**

I've attached Win 7 VM pass and fail logs for the Installation at https://drive.google.com/a/risevision.com/folderview?id=0B9dlQoKNNmZWODd5Yy1lX3MyLW8&usp=sharing

Pass is when I was able to complete the installation and can Start Player. 
Fail is when I was unable to complete the installation.  For this, it was during the 'extracting' message in the UI after I pressed 'Continue' following the network fail check in the UI. 

**In the Pass scenario**
I was able to quickly complete installation without any issues.  The message being shown is clear to me.

**In the Fail scenario**
For this part, the UI 'progress bar' will slowly moved to the halfway point.  As a user (and seeing the progress bar move) it would prompt me to continue waiting...I am not able to tell what the progress is exactly.

In the **installer-events.log** for the **Win 7 Box (not VM)** that passed:

2015/12/22 09:56:01 - beginning install
2015/12/22 09:56:01 - checking components
2015/12/22 09:56:01 - downloading components
2015/12/22 09:56:26 - extracting
2015/12/22 09:56:57 - stopping player and cache
2015/12/22 09:56:57 - stopping chromium
2015/12/22 09:57:00 - removing previous versions
2015/12/22 09:57:00 - installing
2015/12/22 09:57:33 - installing launcher
2015/12/22 09:58:01 - Optimizing OS Settings
2015/12/22 09:58:02 - Optimizing OS Settings
2015/12/22 09:58:02 - Optimizing OS Settings
2015/12/22 09:58:02 - Optimizing OS Settings
2015/12/22 09:58:02 - Optimizing OS Settings
2015/12/22 09:58:02 - Optimizing OS Settings
2015/12/22 09:58:02 - Optimizing OS Settings
2015/12/22 09:58:02 - Optimizing OS Settings
2015/12/22 09:58:02 - Optimizing OS Settings
2015/12/22 09:58:02 - Optimizing OS Settings
2015/12/22 09:58:03 - Optimizing OS Settings
2015/12/22 09:58:03 - Optimizing OS Settings
2015/12/22 09:58:03 - Optimizing OS Settings
2015/12/22 09:58:03 - Optimizing OS Settings
2015/12/22 09:58:03 - Optimizing OS Settings
2015/12/22 09:58:04 - install complete

In the **installer-events.log** for VM1 that progressed slowly (due to network)

2015/12/21 22:41:49 - beginning install
2015/12/21 22:41:49 - checking components
2015/12/21 22:42:05 - downloading components
2015/12/21 23:04:50 - extracting
2015/12/22 02:02:55 - stopping player and cache
2015/12/22 02:09:26 - stopping chromium
2015/12/22 02:11:57 - removing previous versions
2015/12/22 02:11:57 - installing
2015/12/22 02:34:26 - installing launcher
2015/12/22 02:40:32 - Optimizing OS Settings
2015/12/22 02:40:33 - Optimizing OS Settings
2015/12/22 02:40:33 - Optimizing OS Settings
2015/12/22 02:40:35 - Optimizing OS Settings
2015/12/22 02:40:35 - Optimizing OS Settings
2015/12/22 02:40:35 - Optimizing OS Settings
2015/12/22 02:40:43 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Setting autostart
2015/12/22 02:41:09 - install complete
2015/12/22 02:42:12 - cache start
2015/12/22 02:42:14 - player start

This stayed on the extracting message for a long time before eventually finishing

In the **installer-events.log** for VM2 that failed:

2015/12/22 10:03:55 - beginning install
2015/12/22 10:03:55 - checking components
2015/12/22 10:03:55 - downloading components
2015/12/22 10:25:09 - extracting
This stayed on the extracting message until I eventually cancelled the process

**Expected outcome**
I am able to know what I should be doing next (ie abort, maintain network connectivity, etc).  For example, if I am waiting for 20 minutes during extraction, should I continue waiting or cancel or seek help?

**Comment by tejohnso** [comment]
@lapinnoir Is there anything special about these machines?  Can you indicate the process you followed?

**Comment by lapinnoir** [comment]
@tejohnso Nothing special, they are all on a clean install of Win 7.  
With one of the failed VMs, it did eventually finish the installation (so, I didn't cancel this - I thought I did) but the whole process took a look time, see **installer-detail.log** for this, which I will update in that folder I shared (cc @fjvallarino)

**VM1 - Initially 
2015/12/21 22:41:49 - beginning install
2015/12/21 22:41:49 - checking components
2015/12/21 22:42:05 - downloading components
2015/12/21 23:04:50 - extracting
2015/12/22 02:02:55 - stopping player and cache
2015/12/22 02:09:26 - stopping chromium
2015/12/22 02:11:57 - removing previous versions
2015/12/22 02:11:57 - installing
2015/12/22 02:34:26 - installing launcher
2015/12/22 02:40:32 - Optimizing OS Settings
2015/12/22 02:40:33 - Optimizing OS Settings
2015/12/22 02:40:33 - Optimizing OS Settings
2015/12/22 02:40:35 - Optimizing OS Settings
2015/12/22 02:40:35 - Optimizing OS Settings
2015/12/22 02:40:35 - Optimizing OS Settings
2015/12/22 02:40:43 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Optimizing OS Settings
2015/12/22 02:40:54 - Setting autostart
2015/12/22 02:41:09 - install complete
2015/12/22 02:42:12 - cache start
2015/12/22 02:42:14 - player start

**Comment by lapinnoir** [comment]
@tejohnso I've just updated the comment.  So a user will eventually finish and go through installation but the messaging is unclear that they can (quality of network or setup would be another conversation - as long as CS/UI can assure the user that they need to wait)

**Comment by tejohnso** [comment]
@lapinnoir The extraction took three hours.  Is it possible there was a lot of contention on that VM? @fjvallarino  In either case, I think we need to improve the UI here so that users know it's still working.

**Comment by lapinnoir** [comment]
@tejohnso @fjvallarino Agree with the UI.
From a CS troubleshooting perspective, knowing that a user can finish installation (ie even after more than a few hours..), CS can state that the user should wait x time and that it may be a network issue as to why it is taking a long time.  

The other item is that I was wondering if the extraction time had something to do with the initial network fail (I pressed 'Continue' for this).  I started running Wireshark during this to see what is being sent in the network during Extraction.  I haven't gone through the logs yet but I noticed something like a TCP keep-alive request to an Amazon IP but need to confirm but I think this is probably outside the scope of this as I still have the proxy boxes left...

The VM set up on two machines - on OSX which holds all the other VMs and a Win 8 machine. I have have a clean install of a Win7 ISO that I also use for other testing - I haven't had issues installing the previous Installer and also CAP on this.

**Comment by lapinnoir** [comment]
@tejohnso 
On the VM that passed (the one on another network) I was able to install on first 2-3 tries, but is pausing considerably on the 'installing' part for nearly an hour now. If this issue is reoccurring on Win7, I would want to test on a few more networks to see if it's related to Win7.

**Comment by fjvallarino** [comment]
@lapinnoir Have you tried the setup process on a real Win 7 machine (not a VM)? I've had some connectivity issues with Win 7 on local VMs, but not on uptimes.

Anyway, the "extracting" and "installing" delays do not involve the network, so it's most likely a hard drive contention issue. We're looking at how we can inform the user the process is still running even if it takes more than expected.

**Comment by lapinnoir** [comment]
@fjvallarino @tejohnso 
For some reason I thought I was working on a VM.  @robb-price has confirmed I am testing on a real Win 7 box not VM.

I've renamed the log files in that folder I shared.

**Comment by tejohnso** [comment]
So @lapinnoir I see some VM fails and a not-VM pass.   Are we only getting failures on VMs?

**Comment by lapinnoir** [comment]
@tejohnso 
There is a definite improvement going away from Win 7 VM on my network and machines. I don’t know what caused one of the delays on the Win 7 real box on Robb’s network- had no delay from download to finish installation but on a reinstall (during the final part of the testing spreadsheet which requires re-installing the Player) there was a considerable delay during the ‘installing’ part in the UI (noted ~hour).  
I would propose looking into testing on other Win 7 VMs/machines and networks in RV - not just first installation but also doing 2-3 subsequent reinstallations.  The issue could be Win 7 related or Win 7 on VMs or just the network.
As long as the user is encouraged to stay around in finishing the install (regardless of x time) that would be good.

**Comment by tejohnso** [comment]
@lapinnoir I just pushed an update which should at least give the UI some updates as the extraction process progresses.  I'll update the trello card soon.

**Comment by tejohnso** [comment]
@lapinnoir please recheck using [340](https://circleci.com/gh/Rise-Vision/rise-launcher-electron/340#artifacts)

**Comment by lapinnoir** [comment]
@tejohnso Rechecking now, can see the new UI.  Will close this issue since it's for 334#artifacts
