### ISSUE TITLE
Could not log to bigquery error

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#39]
**How to duplicate**
This log came from #38 Win7 VM1

After finishing the new Installer (for one of the slow network VM example from #38 ) and starting up the Rise Player, in the logs there is:

Could not log to bq [Error: request to https://www.googleapis.com/bigquery/v2/projects/client-side-events/datasets/Installer_Events/tables/events20151222/insertAll failed, reason: socket hang up]

See installer-detail-Win7-VM1-slownetwork-fail-then-pass.log in https://drive.google.com/drive/folders/0B9dlQoKNNmZWODd5Yy1lX3MyLW8

**Comment by tejohnso** [comment]
@lapinnoir That could've come from a previous attempt to log an error while the network was down.

**Comment by lapinnoir** [comment]
@tejohnso Thanks. I haven't completed the BQ portion for any of the tests yet.  I'll leave this open until I get to this part.

**Comment by lapinnoir** [comment]
reopening if error appears during batch BQ part of installer testing in 360 release
