### ISSUE TITLE
Error message in terminal unclear that errors found in network req is due to being under proxy

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#40]
**How to replicate**
Install

In Terminal:
UI is ready
Checking network requirements
error found5
error found5
error found5
error found4
error found4
error found4
[Hannah: and so on]

The UI pops up prompting user to input proxy information

**Environment**
Ubuntu 14.04 64bit under proxy

**Comment by tejohnso** [comment]
Those are debugging messages which should be removed.  
Updated here https://github.com/Rise-Vision/rise-launcher-electron/pull/123

**Comment by lapinnoir** [comment]
@tejohnso thanks - closing issue
