### ISSUE TITLE
Duplicate rvplayer and rvplayer~ generated 

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#41]
**How to replicate**
I have successfully upgraded from old to new player for the other Ubuntu 14.04 and 15.10 and saw this issue for Ubuntu 15.10 under proxy.  I have done this test twice and can confirm for both.

Note: Testing for this is done on 334#artifacts (Installer Dec 22/2015).  Testing which worked previously was done on 315#artifacts.

Follow the Installer Testing spreadsheet 'Testing previous player to new player upgrade' for Linux (incl editing rvplayer file) until finished (when the Display ID input prompt appears)
Reboot
In /rvplayer/ there are two files **rvplayer** and **rvplayer~**
Open both in gedit.
rvplayer is blank and shown to have 0 bytes
rvplayer~ contains the modified script however it is not shown in File (ie need to press Ctrl+H to view the file) but it is indicated in Terminal.  In properties it is indicated as a "backup file (application/x-trash).
It does not download the new installer and runs it upon reboot.
It still contains the previous RV player files.

**Environment**
Ubuntu 15.10 64bit under proxy

Edit: Ubuntu version edited since it was Ubuntu 15.10 not Ubuntu 14.04

**Comment by tejohnso** [comment]
I suspect that the network failed while the old player was trying to download the new player.  
I just tried this on 14.04 without proxy and it worked as expected.

**Comment by lapinnoir** [comment]
@tejohnso This one was for under proxy only.  It worked without proxy

**Comment by tejohnso** [comment]
Yeah, the old installer has a problem.  It downloads the components list and if it sees the installer needs updating it will start to download the installer.  If at some point that download fails, it leaves a non-functioning, zero byte "rvplayer".  It doesn't handle intermittent network failures well.

**Comment by lapinnoir** [comment]
@tejohnso I'll close this since relates to old Installer and then re-address this if it's in the new Installer and new updater..is that correct?

**Comment by tejohnso** [comment]
@lapinnoir Sure, I'll close it now.
