### ISSUE TITLE
RV Artifacts left after Uninstall command in Startup

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#42]
**How to Duplicate**
Install (334#artifacts)
Select Uninstall Rise Vision Player command in Startup

**Artifacts left:**
Folder including these subfolders: rvplayer > Installer > resources > app > node_modules > https_proxy_agent, istanbul and rimraf subfolders

**Expected outcome:**
No artifacts left

**Environment**
Win 7 32 bit on proxy

**Comment by lapinnoir** [comment]
Edit: I deleted this folder to do another reinstallation of the new Player and could not duplicate.  
I am wondering if this may have been something left over from a previous installation of the new Player? I've noticed that this issue has come up and the folder is **rvplayer** compared to **RVPlayer** folder.

**Comment by tejohnso** [comment]
Maybe a process was still running, preventing the removal of the Installer folder.

**Comment by tejohnso** [comment]
@lapinnoir Is the uninstall ok now?

**Comment by lapinnoir** [comment]
Closing due to new batch testing

**Comment by lapinnoir** [comment]
reopening: https://github.com/Rise-Vision/rise-launcher-electron/pull/130

**Comment by fjvallarino** [comment]
@lapinnoir This one should be working too: https://circleci.com/gh/Rise-Vision/rise-launcher-electron/373#artifacts

**Comment by robb-price** [comment]
@fjvallarino Just to confirm, this issue is now corrected? Can @lapinnoir verify this now?

**Comment by fjvallarino** [comment]
@robb-price As far as my testing goes, yes. The issue referenced previously (#130) is not related to this one.

**Comment by lapinnoir** [comment]
@fjvallarino @robb-price verified - closing this issue
