### ISSUE TITLE
Pop up message when running incorrect arch

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#43]
**How to replicate**
Install 340#artifacts on wrong arch and run (ie 64bit on 32bit)

Message:
This version of %1 is not compatible with the version of Windows you're running.  Check your computer's system information and then contact the software publisher.

**Expected**
Mention it is Rise Vision software and that error is due to arch software (as 'version' could be misinterpreted as Windows 7 or 10 etc)

**Comment by tejohnso** [comment]
I just ran the 64bit Windows version on a 32bit machine and it worked for some reason.

Which machine are you using?  
Did the initial unzip work?

**Comment by tejohnso** [comment]
Correction, I'm going to retest this now.

**Comment by lapinnoir** [comment]
@tejohnso On a real machine - Win 10 32bit

**Comment by fjvallarino** [comment]
@lapinnoir I'm checking if I can improve this message

**Comment by tejohnso** [comment]
@lapinnoir Similar to the linux issue the user should download the correct file.  We can add some workarounds to try to improve this situation if we find out that effort is warranted.

**Comment by lapinnoir** [comment]
@tejohnso Ok - closing until further real world feedback
