### ISSUE TITLE
Uninstall Startup Cmd and Stop Player Startup Cmd

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#44]
**How to Duplicate**
This hasn't surfaced due to how I run the tests on Linux so far where I go to terminal and issue out ./stop.sh and ./uninstall.sh commands on Terminal.

Install 340# artifacts
Issue out the Stop Rise Vision Player and Uninstall Rise Vision Player command on Startup
**rvplayer** artifacts remain.
Uninstall does not Uninstall but issues out pop up to uninstall Rise Vision Player
Stop does stop Player but does not issue out pop up to stop Rise Vision Player

See http://recordit.co/6rANya15ck

Have checked again five minutes later and assets still there

**Environment**
Ubuntu 15.10 64bit but could be applicable with other Linux OS due to how testing was done.
I'll make a note of this in the testing spreadsheet as an FYI

**Comment by tejohnso** [comment]
@lapinnoir Updated [here](https://circleci.com/gh/Rise-Vision/rise-launcher-electron/348#artifacts)

**Comment by lapinnoir** [comment]
@tejohnso Thanks - closing for testing on the new version

**Comment by lapinnoir** [comment]
@tejohnso Verified for 14.04 and 15.10 :+1:
