### ISSUE TITLE
When editing Display ID on the Startup option the Display starts/does not start depending if the DisplayID is valid or invalid

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#45]
**How to Duplicate**

Edit 1:
**Editing from a valid Display ID to an invalid Display ID**
Install using 340#artifacts (but first noted on previous versions)
Start Player upon finish installation and input a valid DisplayID.  Player starts with valid Display ID.

Run "Edit Display ID" Startup option and edit **from a valid Display ID to an invalid Display ID**.  Save.
The Player starts again on the valid (previous) Display.  
See http://recordit.co/lUWnqjMylW

Reboot.  The Player starts on reboot on the invalid Display ID (the one that was edited). 
See http://g.recordit.co/761R8V64g8.gif

Edit 2:
**Editing from an invalid Display ID to a valid Display ID**

Run "Edit Display ID" Startup option and edit the Display ID from the invalid to the valid Display ID. Save. The Player does not start again.

Reboot. The Player starts again on reboot and on the valid Display ID.
See http://g.recordit.co/9VP3DbRoFZ.gif

On previous testing for this part, the edit DisplayID (both for valid and invalid) works on the Displays control panel which shows after initially installing Player.

**Expected outcome**
Does the user need to know that for the Edit to take effect they need to restart the Display instead of waiting for the Player to launch again?

**Environment**
Win 10 64bit

**Comment by tejohnso** [comment]
The player isn't going to pick up a new configuration unless it restarts.  It has no way of knowing that the configuration was edited while it is still running.

Maybe we should have a comment in the file saying so?  
Or maybe the menu option should stop the player before edit and the name should be changed to reflect that?

**Comment by lapinnoir** [comment]
@tejohnso 

I've done the Ctrl+W to stop (or is it pause?) the Player before editing, I thought that Player has stopped (and on restart, will have the DisplayID).  I think that the comment in the file is most straight forward for the user.

**Comment by tejohnso** [comment]
@lapinnoir The CTRL+W will stop the browser/viewer but there's still a java process (player) running in the background.   I'll add a comment in the file.

By the way, how are you starting the player after stopping it?

**Comment by lapinnoir** [comment]
@tejohnso By stop, do you mean Ctrl+W or do you mean the Stop in Start menu? I usually wait until the Player starts again, or go through Installer again.  For this issue, I waited.

**Comment by tejohnso** [comment]
@lapinnoir I've added an issue in the player project for this
https://trello.com/c/Whm2Nb9v

**Comment by lapinnoir** [comment]
@tejohnso Related to this issue: I have found that when a user Edits the Rise Player Configuration, they can Restart Rise Vision Player and their configuration (at least Display ID) will take effect - they don't need to reboot.  I don't know about the other configurations.

**Comment by tejohnso** [comment]
Yeah this is where the *Restart Player* option came from.  
We also need to put a comment in the config file if that hasn't been done yet.

**Comment by lapinnoir** [comment]
@tejohnso I don't think we need to edit the config file comment.  When the user edits, then Saves, they have to Restart Player anyway.
