### ISSUE TITLE
When running Stop > Uninstall in Startup option rvplayer artifacts are left

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#46]
This is related to https://github.com/Rise-Vision/rise-launcher/issues/26 regarding the Uninstall Startup menu item leaving artifacts

**How to Duplicate**
On 340# artifacts
Run Stop Player in Startup menu option.  The Player stops.
Run Uninstall in Startup menu option.  The Player mostly uninstalls but leaves artifacts.  See http://g.recordit.co/vc61f0tCTs.gif http://g.recordit.co/XAGZOOB1wf.gif

The Start menu commands (Edit, Stop, Uninstall Rise Vision) does not appear though.

**Environment**
Win 10 64bit

**Comment by tejohnso** [comment]
@fjvallarino Can you take a look at this one?

**Comment by lapinnoir** [comment]
@tejohnso @fjvallarino 

I've tried this again twice and the Stop > Uninstall works (aka all files deleted).  See http://g.recordit.co/hptBQGTWXu.gif

For the above case, either an anomaly, or another scenario that I haven't replicated in the other two tries recently for Win 10 64bit.

**Comment by tejohnso** [comment]
@lapinnoir Okay I'll close it for now then.
