### ISSUE TITLE
Add a "Start Player" option

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-launcher#47]
We have stop, edit, uninstall, but we don't have **start**.

**Comment by tejohnso** [comment]
@lapinnoir You can check this out [here](https://circleci.com/gh/Rise-Vision/rise-launcher-electron/356#artifacts).  We now have menu commands for uninstall, edit, stop, restart.   
I tested on linux32.

**Comment by lapinnoir** [comment]
@tejohnso confirmed for lnx 64bit 14.04 and 15.10
