### ISSUE TITLE
Installing wrong arch on Linux

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#48]
**How to Duplicate**
Use 348#artifacts 
Run wrong arch on Linux

For 32bit on 64bit arch
```
Removing legacy Rise Vision cron setting
Disabling screensaver
Disabling inactive timeout
./resources/app/initial-run.sh: line 33: /tmp/selfgz1900/resources/app/../../installer: No such file or directory
```

For 64bit on 32bit arch

```
Removing legacy Rise Vision cron setting
Disabling screensaver
Disabling inactive timeout
./resources/app/initial-run.sh: line 33: /tmp/selfgz1794/resources/app/../../installer: cannot execute binary file: Exec format error
```

**Expected**
Should be clear user installing wrong arch

**Comment by tejohnso** [comment]
@lapinnoir There's no nice way to prevent the user from downloading the wrong version or checking which version they've downloaded .I think we should leave this for now and see if it's a real world problem.

**Comment by lapinnoir** [comment]
@tejohnso Ok - closing until further real world feedback
