### ISSUE TITLE
Restart Player Start Menu option not in Windows but is in Linux

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#51]
**How to replicate**
Install 360# artifacts on Windows

No Restart Player option but it is available in Linux 14.04 and 15.10 (ie https://github.com/Rise-Vision/rise-launcher/issues/47)

**Expected**
 Restart Player option in Start menu for Windows

**Comment by fjvallarino** [comment]
@lapinnoir This one is working for me. Just in case, try with this build: https://circleci.com/gh/Rise-Vision/rise-launcher-electron/373#artifacts

**Comment by lapinnoir** [comment]
@fjvallarino I think this is for #42 ?

**Comment by fjvallarino** [comment]
@lapinnoir No no, it's for this one. The Restart menu option is showing up for me.

**Comment by lapinnoir** [comment]
@fjvallarino Looks good. Closing issue.
