### ISSUE TITLE
Zlib._handle.onerror (zlib.js:363:17)

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#53]
**How to replicate**
I initially saw this error on an install on Win 7 32bit, and again on Win 7 64bit.
The popup occurred when I had inadvertently clicked to install the exe during an installation process that is already running. 

```
Uncaught Exception:
Error: an unexpected end of file
at Zlib._handle.onerror (zlib.js:363:17)
```

No observed issues to the user.

**Comment by fjvallarino** [comment]
@lapinnoir Did this happen right away when you ran the installer again, or was it after the installer was loaded and started copying files? I tried launching installer-win-64.exe again with an already running installer and had no issues.

@tejohnso FYI

**Comment by tejohnso** [comment]
@lapinnoir @fjvallarino If this doesn't affect the progress and successful operation of the first run let's close this.

**Comment by lapinnoir** [comment]
@tejohnso @fjvallarino no known affect so will close.

**Comment by lapinnoir** [comment]
@tejohnso @fjvallarino No know effect, will close. Pop up has appeared again, this time on Win 10 for 373#artifacts

**Comment by lapinnoir** [comment]
@tejohnso @fjvallarino I've had this come up across OS.  It happens during the extracting phase. I can confirm that this message will pause the install process until the user clicks OK then the extract process resumes.
