### ISSUE TITLE
Different processes for Win 7 and Win 10 install

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#56]
**How to duplicate**
1x Win 7 VM and 1x Win 10
Go through install for each and run Process Monitor

Background
Win 7 VM has significant delays (i.e. 4 hrs, several hours) in finishing the install.  There were no delays like this noticed in Win 8 and Win 10.  It’s unknown if issue is VM.  In the logs, it looks like the issue may be how Win 7 is going through the install.

Ideas as to why this is the case:
1. Intermittent connectivity: For Win 7 this seems to be true on the starting stages of the install when the components are being downloaded but does not explain why the final stages (ie extracting) has a considerable (ie hours) delay.
2. CPU usage: This could be the issue. I've noticed that CPU for the installer will take up to the high 90s but when I watch both Process Monitor and Process Explorer, it backs down (I've seen 50-60%) when the processes cycle between AppData\Local\Temp\JRE and AppData\Local\Temp\chrome-win-32 processes but I don't know why it would start the cycle (see logs for Win 7).

I think a concern is whether or not this is going to happen on real Win 7 boxes, as I noted that when reinstalling the new Player on a real Win 7 box it delays.

**Win 7 install**
Huge delay in installing.
Seems to initially take place in AppData\Local\Temp\7zS7F38.tmp\ then it starts to create JRE, chrome-win etc temp folders then it cycles between the two.

Note the timestamps:
![delaywin7-1](https://cloud.githubusercontent.com/assets/5868781/12008838/2ca51374-ac27-11e5-8d5e-f8f1df696fcc.png)

Process Monitor log of a Win 7 install
https://drive.google.com/a/risevision.com/file/d/0B9dlQoKNNmZWcTNJZHhJTlJvcFU/view

**Win 10 install**
Seems to take place within AppData\Local\Temp\7zS67DF.tmp\
![win10-install](https://cloud.githubusercontent.com/assets/5868781/12008741/9e29d96a-ac1f-11e5-8e9a-fd71098a219f.png)

Process Monitor log of a Win 10
https://drive.google.com/a/risevision.com/file/d/0B9dlQoKNNmZWWHp1dFpZWDhSQVE/view

**Comment by tejohnso** [comment]
@lapinnoir @fjvallarino Do we have any evidence of this same issue on a real Win7 box as opposed to a VM?

**Comment by lapinnoir** [comment]
@tejohnso This is on Win 7 64 bit and I don't have real machine for Win 7 avail other than Uptime Wall...

**Comment by lapinnoir** [comment]
@tejohnso @fjvallarino Closing since issue on VM but not real Win 7 boxes (both for 32bit and 64bit)
