### ISSUE TITLE
Restart not working on Win 10 but works on Win 7 and 8

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#57]
Use https://circleci.com/gh/Rise-Vision/rise-launcher-electron/383#artifacts

Ctrl+W to get out of viewer
Select Restart
See http://recordit.co/CJi2y4k7uS
In the above example, I’ve tried both the Restart menu option and the Restart in the rvplayer folder itself.  You can see the Terminal flash briefly but the Player not restarting.

I have done another test of this and waited longer and can also confirm.

Verified on Win 7 and 8 though.

cc @fjvallarino

**Comment by fjvallarino** [comment]
@lapinnoir @tejohnso I can restart without problems on my Windows 10 64bit box. I'm downloading a Windows 10 32bit version to create a VM.

**Comment by robb-price** [comment]
@fjvallarino I thought that we had issues with VM's from @lapinnoir 's testing, so we want to avoid those?

@lapinnoir Can you retest this on your Win10 32 bit box? This is the last issue we have to solve.

Thanks!

**Comment by lapinnoir** [comment]
@fjvallarino @robb-price Works on a real box.  Issue seems to be VM so closing this issue
