### ISSUE TITLE
node_modules artifact left after Uninstall

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#58]
**How to Duplicate**
Install https://circleci.com/gh/Rise-Vision/rise-launcher-electron/383#artifacts
Uninstall
Installer app > node_modules > tar-fs
See http://g.recordit.co/VfD7iKTPuq.gif

**Environment**
Win 7 64bit (real box)

**Comment by fjvallarino** [comment]
@lapinnoir @tejohnso I cannot replicate this issue on my Windows 10 64bit box. One thing we can try is waiting a bit more before removing the rvplayer directory after we kill all the processes.

**Comment by lapinnoir** [comment]
@fjvallarino Ok.  Closing issue and I'll keep in mind.
