### ISSUE TITLE
Linux artifacts left in ./config/ after Uninstall

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher#59]
**How to duplicate**
Install
Select Uninstall option
Go to ./config and there is a folder called Installer and chromium.  No identifying content but I have deleted the two folders and ran through the Install process again and these two folders appear.

In **Installer** folder properties
Type: inode/directory
7 files within it
- folder GPUCache
— within the folder binary files (application/octet-stream)
-DevTools Extension

In **chromium** folder properties
Type: inode/directory
1 folder within “Crash Reports”

No known affects to user.
rvplayer is not in Autostart.

**Environment**
Ubuntu 14.04 64bit VM 
Ubuntu 15.10 64bit VM and real box

**Comment by lapinnoir** [comment]
@tejohnso @fjvallarino This can be taken out since this relates to a previous version of Installer.

**Comment by lapinnoir** [comment]
Reopening, to check if this persists in the new Installer version

**Comment by ahmedalsudani** [comment]
@hcs0 after looking into this, we have decided the best option we have is not to change anything.

One of the directories is hard-coded into Chrome, and the other one could not be traced back.

Given their generic names and the fact we don't know what the user used those directories for, deleting them is too risky.
