### ISSUE TITLE
Fonts available in Text Widget in Ubuntu

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-launcher#60]
@tejohnso @fjvallarino I'm not sure where to put this - ie if in Text Widget or in the Rise Launcher but there is a Trello card about adding MSFT fonts to Ubuntu in Installer Improvements so I thought to add it here.

**How to Duplicate**
In Text Widget:
1. Add the main fonts (top)
2. Add a sample of fonts from 'More Fonts' (middle)
3. Add a sample from custom fonts (TIFF) (bottom)
See http://rva.risevision.com/#/PRESENTATION_MANAGE/id=7f133695-1c2f-4040-9f43-7318fe6ad06d?cid=960b72df-9af7-476b-8a47-b67ded4c779d

See in preview:
<img width="623" alt="screen shot 2015-12-30 at 8 02 51 pm" src="https://cloud.githubusercontent.com/assets/5868781/12059803/5fcfc1d4-af30-11e5-8ebe-8461da339f80.png">

In Ubuntu:

<img width="913" alt="screen shot 2015-12-30 at 7 33 48 pm" src="https://cloud.githubusercontent.com/assets/5868781/12059806/6aafcfd6-af30-11e5-930c-b9adf14ea326.png">

**Microsoft Core Fonts TTF Package in Ubuntu**

I tried the following but failed to download the package looks like a 404 at the source:

Step 1:
Looked for **ttf-mscorefonts** in the Ubuntu Software Centre
Getting a failed to download message

Step 2: Reinstall

````
sudo dpkg -P ttf-mscorefonts-installer  
sudo apt-get install ttf-mscorefonts-installer
````

Which then prompted some sort of EULA that one is supposed to agree to:

<img width="728" alt="screen shot 2015-12-30 at 7 54 48 pm" src="https://cloud.githubusercontent.com/assets/5868781/12059763/96892b58-af2f-11e5-9d96-7fadf662b9f8.png">

After selecting Yes, then getting a message as to why download failed:

````
Preparing to unpack .../ttf-mscorefonts-installer_3.4+nmu1ubuntu2_all.deb ...
Unpacking ttf-mscorefonts-installer (3.4+nmu1ubuntu2) ...
Processing triggers for fontconfig (2.11.1-0ubuntu6) ...
Processing triggers for update-notifier-common (3.163) ...
ttf-mscorefonts-installer: downloading http://downloads.sourceforge.net/corefonts/andale32.exe
Err http://downloads.sourceforge.net/corefonts/andale32.exe
  404  Not Found
E: Failed to fetch http://downloads.sourceforge.net/corefonts/andale32.exe 404  Not Found

E: Download Failed
````

**Extra notes for fonts**
- It looks like it's difficult to support the main fonts in the Text widget (within the Installer optimization) unless the user uses a custom font URL in which case it will show.
- In Dev Tools > Resources > Frames > Viewer.html > in the specific widget.hml the 'more fonts' are calling out to an external source in the CSS ie https://fonts.gstatic.com/ whereas the main font choices are not

**Comment by lapinnoir** [comment]
FYI @btfrise

**Comment by lapinnoir** [comment]
@tejohnso @fjvallarino Since there's a card about this already, I will close this issue.

**Comment by hcs0** [comment]
Resolved in Linux x64
@btfrise I've updated the presentation link since the older one used the previous version of the Text Widget
