### ISSUE TITLE
When the user goes to install Rise Player, we need to improve the message that shows if CAP Player is currently installed

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-launcher#62]
**How it works now:**
1. Confirm that your Display currently has CAP installed.
2. Download and run the electron Rise Player installer on this machine. Notice that you get this error:
![capinstallerrormessage](https://cloud.githubusercontent.com/assets/5868781/12173101/e290fbe0-b522-11e5-807f-e9d3b2fa6f5c.png)

**How it should work:**
The User should not have to go to Community for assistance. Instead, the text could say the following: <i>Installation cannot proceed since the Rise Chrome App Player is currently installed. To remove it, open Google Chrome, navigate to <b>chrome://apps</b>, and remove the Rise Vision Chrome App Player. Once that is completed, please proceed with the install again.</i>

**Comment by lapinnoir** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/conversation/1570106116

**Comment by lapinnoir** [comment]
Also for https://app.intercom.io/a/apps/d85f4ah4/inbox/hcs@risevision.com/conversations/1681726824 (another use).  User attempted to install twice, got the CAP message, then third install attempt it went through

**Comment by lapinnoir** [comment]
@fjvallarino @tejohnso Is it possible at all to get a "Cannot proceed with install message due to CAP that already exists on this Display" message if a user is on Ubuntu?  I saw this message when I was doing an install of the Rise Linux Player on an existing Display (and didn't realize that they already had the Player).  Thanks!

**Comment by robb-price** [comment]
@lapinnoir I don't know (and I assume @fjvallarino and @tejohnso won't know either) what currently happens, and what change you re proposing. Can you update the above description to match this format:

<b>How it works now:</b>
XX
<b>How it should work:</b>
XX
I want to keep that same format on all issues we log so we have a clear understanding of what the issue/enhancement is, so it is clear and concise.

**Comment by lapinnoir** [comment]
@robb-price I've just edited the original issue and also for https://github.com/Rise-Vision/rise-launcher/issues/63 to include the **How it works now:** and **How it should work:**

The comment about the CAP message on Linux shouldn't be there so I'll look into that and log it end of today.

**Comment by robb-price** [comment]
@lapinnoir I made some changes to your description. Let me know if that makes sense, and is indicative of the issue.

**Comment by fjvallarino** [comment]
@lapinnoir @robb-price just to be sure: the change we should implement is the message we display to the user, right?

@tejohnso FYI

**Comment by robb-price** [comment]
@fjvallarino That is correct.

Thanks!

**Comment by lapinnoir** [comment]
@fjvallarino Yes that is correct.  This has come up now with users not knowing how to uninstall CAP so at least that is one less obstacle for them to install the new Player.  Thanks

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;m4oIdP1J&#x2F;871-issue-62-when-the-user-goes-to-install-rise-player-we-need-to-improve-the-message-that-shows-if-cap-player-is-currently-installe"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Issue #62 When the user goes to install Rise Player, we need to improve the message that shows if CAP Player is currently installed</a>

**Comment by ahmedalsudani** [comment]
To test this has been verified:

- open Chrome (If you don't have it installed, open the Chrome that the Player uses. You can find it in the `rvplayer` directory)
- Install Chrome App Player from https://chrome.google.com/webstore/detail/rise-player/ilcmohdkjfcfekfmpdppgoaaemgdmhaa?hl=en
- Restart the player
- Verify the message has changed from the one above and now shows https://github.com/Rise-Vision/rise-launcher-electron/blob/stage/release-branch/installer/ui/messages/cap-installed.md

**Comment by btfrise** [comment]
Confirmed as changed.
