### ISSUE TITLE
Users unable to launch new version of Rise Player

### ISSUE THREAD

**Issue by ashleighalmeida** [Rise-Vision/rise-launcher#69]
<b>How it works now:</b>

1. User installs the newest version of Installer when they already have an existing Rise Vision Player installation / automated deployment of the version change 2015.10.12.15.11 has been rolled out to the user
2. User launches player, and get's an error. ("An unknown error has occurred. Please try again or post a question to http://community.risevision.com")
3. User removes all existing instances of the rvplayer folders from previous version, and reinstalls the newest version of player.
4. User is able to run the new version of player.

![img_2182](https://cloud.githubusercontent.com/assets/11686685/12683516/b8b33b32-c687-11e5-87da-56577af6e41f.JPG)

<b>How it should work:</b>

There are no issues when installing Player if an existing installation exists.

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Xr5Q1G8m&#x2F;870-issue-69-users-unable-to-launch-new-version-of-rise-player"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Issue #69 Users unable to launch new version of Rise Player</a>

**Comment by ByronDarlison** [comment]
Duplicate issue of https://github.com/Rise-Vision/rise-launcher-electron/issues/155 Closing
